### ISSUE TITLE
tests folder doesn't exist for cs fixer

### ISSUE THREAD

**Issue by hwaseonchoi** [adaniloff/symfony-bootstrap#1]
Hello, 

I'm using this template and my symfony configuration is as basic as you configured in `composer.json`, so `/tests` folder is not included but your cs fixer in `Makefile` is extended to `/tests` folder also. 

The error message is ` The path "tests/" is not readable.`

Is there any way to not include if sf5 config doesn't include `/tests` or to check folders to fix dynamically ? 

Thanks :)

**Comment by adaniloff** [comment]
I'll try to make an improvement that will fix the issue.

`make fix-cs` will then be able to take arguments, representing the folder in which we want to run the fixer ; the syntax would probably something like `make fix-cs dir1 [dir2 [dir3]]`. 

No argument at all would then display a message and advice to try `make fix-cs src/`.

What do you think about that ?

In the meantime, if that blocks you, you can always change your own Makefile (in your project) in order to fix this issue :)
